# Generated by Django 4.0.4 on 2022-04-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'verbose_name': 'Способ получения', 'verbose_name_plural': 'Способы получения'},
        ),
        migrations.AlterModelOptions(
            name='paymenttype',
            options={'verbose_name': 'Вид оплаты', 'verbose_name_plural': 'Виды оплат'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='deliverytype',
            name='for_bot',
            field=models.BooleanField(default=False, verbose_name='Для бота магазина'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='for_bot',
            field=models.BooleanField(default=False, verbose_name='Для бота магазина'),
        ),
        migrations.AlterField(
            model_name='status',
            name='for_bot',
            field=models.BooleanField(default=False, verbose_name='Для бота магазина'),
        ),
    ]
