# Generated by Django 4.0.4 on 2022-04-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_deliverytype_options_alter_paymenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Услуга'),
        ),
    ]
