# Generated by Django 4.0.2 on 2022-02-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_products',
            field=models.ManyToManyField(blank=True, related_name='get_cart', to='shop.CartProduct', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_products',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Общее количество'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='Количество'),
        ),
    ]
