# Generated by Django 4.0.2 on 2022-02-21 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_cartproduct_discount_cartproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_cart_products', to='shop.cart', verbose_name='Корзина'),
        ),
    ]
