# Generated by Django 4.0.2 on 2022-02-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_time_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_products',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='Анонимный покупатель'),
        ),
    ]
