# Generated by Django 4.0.2 on 2022-02-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='phone_anonymous',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон из Telegram'),
        ),
    ]
