# Generated by Django 4.0.2 on 2022-02-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cartproduct_phone_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='phone_anonymous',
            field=models.CharField(default='', max_length=15, verbose_name='Телефон из мессенджера'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
    ]
