# Generated by Django 4.0.2 on 2022-02-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cartproduct_phone_anonymous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='phone_anonymous',
        ),
        migrations.AddField(
            model_name='cart',
            name='phone_anonymous',
            field=models.CharField(default='', max_length=15, verbose_name='Телефон из мессенджера'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='id_anonymous',
            field=models.CharField(default='', max_length=10, verbose_name='ID из мессенджера'),
        ),
    ]
