# Generated by Django 4.0.2 on 2022-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_cartproduct_phone_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='id_anonymous',
            field=models.IntegerField(default=0, verbose_name='ID из мессенджера'),
        ),
    ]
