# Generated by Django 4.0.2 on 2022-02-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_cartproduct_id_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone_anonymous',
        ),
        migrations.AddField(
            model_name='order',
            name='id_anonymous',
            field=models.IntegerField(default=0, verbose_name='ID из мессенджера'),
        ),
    ]
