# Generated by Django 4.0.3 on 2022-04-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_cart_phone_anonymous_order_id_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_products',
        ),
    ]
