# Generated by Django 4.0.3 on 2022-04-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_cart_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Скидка %'),
        ),
    ]
